# Generated by Django 4.1.5 on 2023-01-13 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        editable=False,
                        null=True,
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("event_type", models.TextField()),
                ("descriptions", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[("In", "Info"), ("At", "Attention"), ("Al", "Alarm")],
                        default="In",
                        max_length=2,
                    ),
                ),
                (
                    "tagM2M",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.tag"
                    ),
                ),
            ],
        ),
    ]
