# Generated by Django 4.1.5 on 2023-01-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.TextField(),
        ),
    ]
