# Generated by Django 4.1.5 on 2023-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_tag_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="tagM2M",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=128),
        ),
    ]
